export const runtime = 'nodejs';

import { NextRequest, NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/supabase-admin';
import { requireWorkspaceAccess } from '@/lib/require-workspace-access';
import { encryptSenderSecret, decryptSenderSecret } from '@/lib/smtp-credentials';
import { testSmtpConnection } from '@/lib/smtp-client';
import { normalizeEmailAddress } from '@/lib/email-verification';

function safeAccount(row: any) {
  return {
    id: row.id,
    workspace_id: row.workspace_id,
    email: row.email,
    display_name: row.display_name,
    status: row.status,
    auth_mode: row.auth_mode || 'oauth',
    smtp_host: row.smtp_host || null,
    smtp_port: row.smtp_port || null,
    smtp_verified_at: row.smtp_verified_at || null,
    daily_limit: row.daily_limit ?? null,
    default_run_limit: row.default_run_limit ?? null,
    sent_today: row.sent_today ?? null,
    last_error: row.last_error || null,
    created_at: row.created_at,
    updated_at: row.updated_at,
  };
}

function errorMessage(error: unknown) {
  return error instanceof Error ? error.message : String(error || 'Unknown error');
}

export async function GET(request: NextRequest) {
  try {
    const workspaceId = String(request.nextUrl.searchParams.get('workspace_id') || '');
    await requireWorkspaceAccess(workspaceId);
    const supabase = createAdminClient();
    const { data, error } = await supabase
      .from('gmail_accounts')
      .select('id,workspace_id,email,display_name,status,auth_mode,smtp_host,smtp_port,smtp_verified_at,daily_limit,default_run_limit,sent_today,last_error,created_at,updated_at')
      .eq('workspace_id', workspaceId)
      .order('created_at', { ascending: true });
    if (error) throw error;
    return NextResponse.json({ accounts: (data || []).map(safeAccount) });
  } catch (error) {
    return NextResponse.json({ error: errorMessage(error) }, { status: Number((error as any)?.status || 400) });
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const workspaceId = String(body.workspace_id || '');
    const action = String(body.action || 'connect');
    const { user } = await requireWorkspaceAccess(workspaceId);
    const supabase = createAdminClient();

    if (action === 'disconnect') {
      const id = String(body.account_id || '');
      if (!id) throw new Error('account_id is required.');
      const { error } = await supabase.from('gmail_accounts').update({
        status: 'disconnected',
        smtp_secret_ciphertext: null,
        smtp_secret_iv: null,
        smtp_secret_tag: null,
        last_error: null,
        updated_at: new Date().toISOString(),
      }).eq('workspace_id', workspaceId).eq('id', id);
      if (error) throw error;
      return NextResponse.json({ success: true });
    }

    if (action === 'test') {
      const id = String(body.account_id || '');
      const { data: account, error } = await supabase
        .from('gmail_accounts')
        .select('*')
        .eq('workspace_id', workspaceId)
        .eq('id', id)
        .single();
      if (error || !account) throw new Error(error?.message || 'Sender account not found.');
      if (String(account.auth_mode || '') !== 'smtp') throw new Error('This sender is not configured for SMTP.');
      const password = decryptSenderSecret({
        ciphertext: String(account.smtp_secret_ciphertext || ''),
        iv: String(account.smtp_secret_iv || ''),
        tag: String(account.smtp_secret_tag || ''),
      });
      await testSmtpConnection({
        host: String(account.smtp_host || 'smtp.gmail.com'),
        port: Number(account.smtp_port || 465),
        username: String(account.email),
        password,
      });
      await supabase.from('gmail_accounts').update({
        status: 'connected',
        smtp_verified_at: new Date().toISOString(),
        last_error: null,
        updated_at: new Date().toISOString(),
      }).eq('workspace_id', workspaceId).eq('id', id);
      return NextResponse.json({ success: true });
    }

    const email = normalizeEmailAddress(body.email);
    const displayName = String(body.display_name || '').trim().slice(0, 120);
    const appPassword = String(body.app_password || '').replace(/\s+/g, '');
    const host = String(body.smtp_host || 'smtp.gmail.com').trim().toLowerCase();
    const port = Number(body.smtp_port || 465);
    if (!email) throw new Error('Enter a valid Gmail address.');
    if (!appPassword || appPassword.length < 12) throw new Error('Enter the Gmail App Password generated by Google.');
    if (host !== 'smtp.gmail.com' || port !== 465) throw new Error('This setup currently supports Gmail through smtp.gmail.com on port 465.');

    await testSmtpConnection({ host, port, username: email, password: appPassword });
    const encrypted = encryptSenderSecret(appPassword);
    const now = new Date().toISOString();

    const { data, error } = await supabase.from('gmail_accounts').upsert({
      workspace_id: workspaceId,
      email,
      display_name: displayName || email.split('@')[0],
      status: 'connected',
      auth_mode: 'smtp',
      smtp_host: host,
      smtp_port: port,
      smtp_secure: true,
      smtp_secret_ciphertext: encrypted.ciphertext,
      smtp_secret_iv: encrypted.iv,
      smtp_secret_tag: encrypted.tag,
      smtp_verified_at: now,
      access_token: null,
      refresh_token: null,
      expires_at: null,
      granted_scopes: [],
      oauth_reconnect_required: false,
      connection_status: 'connected',
      connection_verified_at: now,
      connection_error: null,
      last_error: null,
      created_by: user.id,
      updated_at: now,
    }, { onConflict: 'workspace_id,email' }).select('*').single();
    if (error) throw error;

    return NextResponse.json({ success: true, account: safeAccount(data) });
  } catch (error) {
    return NextResponse.json({ error: errorMessage(error) }, { status: Number((error as any)?.status || 400) });
  }
}
